#!/usr/bin/env python3
"""
FaizxAi Bot — Auto Setup Script
Run this once after cloning the repo.
It handles everything: Python check, pip install, .env setup, then launches the bot.
"""

import sys
import os
import subprocess
import shutil

# ──────────────────────────────────────────────────────────────────────────────
# ANSI colours — because dry setup output is the enemy
# ──────────────────────────────────────────────────────────────────────────────
R  = "\033[91m"   # red
G  = "\033[92m"   # green
Y  = "\033[93m"   # yellow
B  = "\033[94m"   # blue
M  = "\033[95m"   # magenta
C  = "\033[96m"   # cyan
W  = "\033[97m"   # white
BLD= "\033[1m"
RST= "\033[0m"

BANNER = f"""
{M}{BLD}
███████╗ █████╗ ██╗███████╗██╗  ██╗ █████╗ ██╗
██╔════╝██╔══██╗██║╚══███╔╝╚██╗██╔╝██╔══██╗██║
█████╗  ███████║██║  ███╔╝  ╚███╔╝ ███████║██║
██╔══╝  ██╔══██║██║ ███╔╝   ██╔██╗ ██╔══██║██║
██║     ██║  ██║██║███████╗██╔╝ ██╗██║  ██║██║
╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
{RST}{C}   FaizxAi Discord Bot — Auto Setup v1.0{RST}
{Y}   github.com/Faizxdev/FaizxAi{RST}
"""

def banner():
    print(BANNER)

def step(msg):
    print(f"\n{B}{BLD}[SETUP]{RST} {W}{msg}{RST}")

def ok(msg):
    print(f"  {G}✓{RST} {msg}")

def warn(msg):
    print(f"  {Y}⚠{RST}  {msg}")

def err(msg):
    print(f"  {R}✗{RST}  {msg}")
    sys.exit(1)

def ask(prompt, default=None):
    hint = f" [{default}]" if default else ""
    val = input(f"  {C}→{RST} {prompt}{hint}: ").strip()
    return val if val else default

# ──────────────────────────────────────────────────────────────────────────────
# 1. Python version check
# ──────────────────────────────────────────────────────────────────────────────
def check_python():
    step("Checking Python version...")
    v = sys.version_info
    if v.major < 3 or (v.major == 3 and v.minor < 10):
        err(f"Python 3.10+ required. You have {v.major}.{v.minor}.{v.micro}")
    ok(f"Python {v.major}.{v.minor}.{v.micro} — good to go")

# ──────────────────────────────────────────────────────────────────────────────
# 2. Install dependencies
# ──────────────────────────────────────────────────────────────────────────────
def install_requirements():
    step("Installing Python requirements...")
    req_file = os.path.join(os.path.dirname(__file__), "requirements.txt")
    if not os.path.exists(req_file):
        err("requirements.txt not found — is this the project root?")
    
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-r", req_file, "--quiet", "--upgrade"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        warn("pip install had warnings/errors:")
        print(result.stderr[-1000:])
    else:
        ok("All requirements installed successfully")

# ──────────────────────────────────────────────────────────────────────────────
# 3. .env setup
# ──────────────────────────────────────────────────────────────────────────────
def setup_env():
    step("Setting up .env configuration...")
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    example_path = os.path.join(os.path.dirname(__file__), ".env.example")

    if os.path.exists(env_path):
        print(f"  {Y}⚠{RST}  .env already exists — skipping creation")
        print(f"       Edit {C}.env{RST} manually if you need to update values.")
        return

    print(f"\n{BLD}{W}  Let's configure your bot. Fill in the values below:{RST}")
    print(f"  {Y}(Leave blank to fill in the .env manually later){RST}\n")

    fields = {
        "DISCORD_TOKEN":      ("Discord Bot Token",                          None),
        "GUILD_ID":           ("Discord Server (Guild) ID",                  None),
        "LOG_LEVEL":          ("Log level",                                  "INFO"),
        "PRIVILEGED_INTENTS": ("Enable privileged intents? (true/false)",    "true"),
        "AI_PROVIDER":        ("AI Provider (bluesminds / openai / gemini)", "bluesminds"),
        "BLUESMINDS_API_KEY": ("Bluesminds API Key",                         None),
        "BLUESMINDS_BASE":    ("Bluesminds Base URL",                        "https://api.bluesminds.com/v1"),
        "BLUESMINDS_MODEL":   ("Bluesminds Model",                           "gpt-5.5"),
        "OPENAI_API_KEY":     ("OpenAI API Key (optional, press Enter to skip)", ""),
        "GEMINI_API_KEY":     ("Google Gemini API Key (optional)",           ""),
        "CASTAI_API_KEY":     ("CastAI API Key (optional)",                  ""),
        "CONFIG_PATH":        ("Config file path",                           "src/config/server.yml"),
    }

    env_lines = ["# FaizxAi Bot — Generated by setup.py\n"]
    for key, (label, default) in fields.items():
        val = ask(label, default)
        env_lines.append(f"{key}={val}\n")

    with open(env_path, "w") as f:
        f.writelines(env_lines)

    ok(".env created successfully!")

# ──────────────────────────────────────────────────────────────────────────────
# 4. Verify src structure exists
# ──────────────────────────────────────────────────────────────────────────────
def verify_structure():
    step("Verifying project structure...")
    required = ["src", "src/bot.py", "src/core", "src/commands", "src/utils"]
    for path in required:
        full = os.path.join(os.path.dirname(__file__), path)
        if not os.path.exists(full):
            err(f"Missing required path: {path} — clone may be incomplete")
    ok("Project structure looks good")

# ──────────────────────────────────────────────────────────────────────────────
# 5. Create logs directory
# ──────────────────────────────────────────────────────────────────────────────
def create_dirs():
    step("Creating runtime directories...")
    os.makedirs("logs", exist_ok=True)
    ok("logs/ directory ready")

# ──────────────────────────────────────────────────────────────────────────────
# 6. Launch bot
# ──────────────────────────────────────────────────────────────────────────────
def launch_bot():
    print(f"\n{G}{BLD}══════════════════════════════════════════════════{RST}")
    print(f"{G}{BLD}   ✅  Setup complete! Launching FaizxAi Bot...    {RST}")
    print(f"{G}{BLD}══════════════════════════════════════════════════{RST}\n")
    
    bot_path = os.path.join(os.path.dirname(__file__), "src", "bot.py")
    os.execv(sys.executable, [sys.executable, bot_path])

# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    banner()

    check_python()
    install_requirements()
    verify_structure()
    create_dirs()
    setup_env()

    print(f"\n{C}{'─' * 50}{RST}")
    launch_prompt = input(f"\n{BLD}  Launch the bot now? (y/n) [{G}y{RST}{BLD}]:{RST} ").strip().lower()
    if launch_prompt in ("", "y", "yes"):
        launch_bot()
    else:
        print(f"\n  {Y}Run manually:{RST}  {C}python src/bot.py{RST}\n")
